[package]
name = "watch-folder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "6.1.1"
env_logger = "0.10.0"
log = "0.4.17"
daemonize = "0.5.0"
yaml-rust = "0.4.5"
