config:
  watch:
    - path: ~/Downloads
    # - path: ~/Desktop
  file-types:
    documents:
      - pdf
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
      - txt
      - md
      - html
      - drawio
    images:
      - jpg
      - jpeg
      - png
      - gif
      - tiff
      - bmp
      - svg
      - webp
      - ico
    videos:
      - mp4
      - mov
      - avi
      - mkv
      - flv
      - m4v
      - rmvb
      - rm
      - 3gp
      - mpg
      - mpeg
      - webm
    audios:
      - mp3
      - wav
      - wma
      - ogg
      - m4a
      - aac
      - aiff
    installers:
      - exe
      - msi
      - iso
      - dmg
      - pkg
      - deb
      - rpm
      - appimage
    archives:
      - zip
      - tar
      - gz
      - rar
      - 7z
      - bz2
      - xz
      - tgz
    code:
      - yml
      - yaml
      - conf
      - json
      - js
      - ts
      - py
      - rs
      - css
      - sh
    misc:
      - winmd
  ignore-extensions:
    - crdownload
    - part
    - download
    - opdownload
    - tmp
    - partial
  stability:
    interval-ms: 1000
    required-stable-ticks: 2
